# Arrays


In [ ]:
# array class are mutable and behave similarly to lists
# -- except 
# they are “typed arrays” constrained to a single data type.
# array objects with many elements are more space-efficient than lists and tuples.

# -- mutable
# -- ordered
# -- indexing is possible
# -- single datatype elements


![Alt text](arrays.png)

# Built-in Array

In [1]:
import array as arr
a = arr.array('i',[]) # empty array
print(type(a)) # array.array says that it is a built-in array


<class 'array.array'>


In [3]:
from array import *

vals1 = array('i',[5,9,8,6,4,3]) # i refers to integer
print(vals1)
print(type(vals1))

# vals2 = array('i',[5,9,8,6.2,4,3]) # error. if we add a float value
# print(vals2)

vals3 = array('i',[5,9,-4,3]) # it is ok with negative values
print(vals3)

# vals4 = array('I',[9,6,5,2,-1]) # error. 'I' refers to unsigned integer. it does not take negative values.


array('i', [5, 9, 8, 6, 4, 3])
<class 'array.array'>
array('i', [5, 9, -4, 3])


In [3]:

print(vals1.buffer_info()) # gives a tuple (adress, size)

print(vals1.typecode)


(1729295598896, 6)
i


In [4]:

vals1.reverse()
print('reversed',vals1)

# indexing
print(vals1[0])


reversed array('i', [3, 4, 6, 8, 9, 5])
3


In [4]:

for i in range(len(vals3)):
    print(vals3[i])

print()

for e in vals3:
    print(e)


5
9
-4
3

5
9
-4
3


In [5]:

vals5 = array('u',['a','e','i','o','u']) # unicode character
print(vals5)

print()
newArr = array(vals1.typecode,(a for a in vals1))
print(newArr)

print()
newArr1 = array(vals1.typecode,(a*a for a in vals1))
print(newArr1)

i=0
while i<len(newArr):
    print(newArr[i])
    i+=1
  

array('u', 'aeiou')

array('i', [5, 9, 8, 6, 4, 3])

array('i', [25, 81, 64, 36, 16, 9])
5
9
8
6
4
3


In [7]:
# creating an array with for loop ( append() )

from array import *

arr = array('i',[])

n = int(input('enter the length of the array: '))

for i in range(n):
    x = int(input('enter the next value: '))
    arr.append(x) 

print(arr)


array('i', [1, 1])


In [8]:

val = int(input('enter the value for search: '))

k=0
for e in arr:
    if e==val:
        print(k) # gives the index of first occurance of the values that we are finding
        break
    k+=1
    
print(arr.index(val)) # gives the index of the values that we are finding

ValueError: array.index(x): x not in array

In [ ]:
from array import *

# arr = array('i',[1,2,3],[2,5,6]) # error -- multi-dimensional array does not work in built-in array


# Numpy Array

In [ ]:
# search for Python – Built-in array vs NumPy array on GFG.
# built-in array has only single dimensional array that is one row and one column. [1,2,3,4]
# numpy has multi dimensional arrays. that is multiple rows and multiple arrays. ex. matrix 

In [ ]:
# pip install numpy

In [10]:
from numpy import *

arr1 = array ([1,2,3,4,5,6])
arr2 = array([6,7,9,1,2,3])

arr1 = arr1 + 5 # all the elements are added with 5
print(arr1)

arr3 = arr1 + arr2 # elements corresponding to similar index get added
print(arr3)

print(type(arr1)) # numpy.ndarray says it is an array from numpy liberary

[ 6  7  8  9 10 11]
[12 14 17 10 12 14]
<class 'numpy.ndarray'>


In [11]:
import numpy as np

# create a 1-dimensional Numpy array of strings
strings = np.array(["apple", "banana", "orange"], dtype=str) 


print(strings)  # compare this output with the built-in array

# indexing
print(strings[0])  # apple

# modify an element of the array
strings[0] = "pear"
print(strings)  


['apple' 'banana' 'orange']
apple
['pear' 'banana' 'orange']


In [12]:
integer = np.array([10,20,30],dtype=int) # it works even if we do not mention dtype

print(integer)
print(type(integer))

[10 20 30]
<class 'numpy.ndarray'>


In [14]:
# there are various mathematical functions in numpy that we can use
print(arr2)

print(sin(arr2))
print(cos(arr2))
print(log(arr2))
print(sqrt(arr2))
print(min(arr2))
print(max(arr2))
print(sort(arr2))
print(concatenate([arr1,arr2]))


[6 7 9 1 2 3]
[-0.2794155   0.6569866   0.41211849  0.84147098  0.90929743  0.14112001]
[ 0.96017029  0.75390225 -0.91113026  0.54030231 -0.41614684 -0.9899925 ]
[1.79175947 1.94591015 2.19722458 0.         0.69314718 1.09861229]
[2.44948974 2.64575131 3.         1.         1.41421356 1.73205081]
1
9
[1 2 3 6 7 9]
[ 6  7  8  9 10 11  6  7  9  1  2  3]


Different ways of creating array in numpy

In [15]:
# 1. using array([])

from numpy import *   # here * imports all the functions in the numpy which consumes more data. instead you can use (from numpy import array)

arr = array([11,12])
print(arr)
print(arr.dtype)

arr1 = array([11,12,12.0])
print(arr1)
print(arr1.dtype)

arr2 = array([11,12],float)
print(arr2)
print(arr2.dtype)


[11 12]
int32
[11. 12. 12.]
float64
[11. 12.]
float64


In [16]:
# 2. empty array

arr = array([])
print(arr)
print(type(arr))


[]
<class 'numpy.ndarray'>


In [17]:
# 3. using linespace

arr3 = linspace(0,16,10) # 10 paths
print(arr3)

arr4 = linspace(0,15,16)
print(arr4)

arr5 = linspace(0,15,20)
print(arr5)

arr5 = linspace(0,49) # if we do not specify by default it takes 50 parts
print(arr5)

arr5 = linspace(0,20)
print(arr5)


[ 0.          1.77777778  3.55555556  5.33333333  7.11111111  8.88888889
 10.66666667 12.44444444 14.22222222 16.        ]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]
[ 0.          0.78947368  1.57894737  2.36842105  3.15789474  3.94736842
  4.73684211  5.52631579  6.31578947  7.10526316  7.89473684  8.68421053
  9.47368421 10.26315789 11.05263158 11.84210526 12.63157895 13.42105263
 14.21052632 15.        ]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]
[ 0.          0.40816327  0.81632653  1.2244898   1.63265306  2.04081633
  2.44897959  2.85714286  3.26530612  3.67346939  4.08163265  4.48979592
  4.89795918  5.30612245  5.71428571  6.12244898  6.53061224  6.93877551
  7.34693878  7.75510204  8.16326531  8.57142857  8.97959184  9.3877551
  9.79591837 10.20408163 10.6122449  11.02040816 11.42857143 11.8367346

In [18]:
# 4. using arange

arr6 = arange(1,15,2) # 2 steps
print(arr6)
print(type(arr6))


[ 1  3  5  7  9 11 13]
<class 'numpy.ndarray'>


In [19]:
# 5. using logspace

arr7 = logspace(1,40,5) # it starts from 10^1 to 10^40 and it will get divided into 5 parts
print(arr7)
print('%.2f'%arr7[0])
print('%.2f'%arr7[4]) # prints the whole thing without converting it into power format


[1.00000000e+01 5.62341325e+10 3.16227766e+20 1.77827941e+30
 1.00000000e+40]
10.00
10000000000000000303786028427003666890752.00


In [20]:
# 6. using zeros, ones

arr8 = zeros(5)
print(arr8)

arr9 = ones(5)
print(arr9)

arr10 = ones(5,int)
print(arr10)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1 1 1 1 1]


Copying array


In [21]:
# 1. using "="

arr4 = arr2
print(arr4)
print(arr2)

print(id(arr4))
print(id(arr2)) # same id

# both of this have same address. that is both are pointing to the same array. 
# it is like creating an alis.
# in python objects are alloted a particular id any variable refering to that object will show that id.

[11. 12.]
[11. 12.]
1729541731600
1729541731600


In [22]:
# 2. using view (shallow copy)

# what if we want to create a new array at a different address?
arr5 = arr2.view()
print(id(arr5))
print(id(arr2)) # different id

# shallow copy -- it means that it will copy the array and both the arrays are still dependent on eachother.
arr2[0] = 67
print(arr5,arr2) # the value is changed for both 


1729541732464
1729541731600
[67. 12.] [67. 12.]


In [23]:
# 3. using copy (deep copy)

# deep copy -- change in one array does not effect the other.
arr6 = arr2.copy()
print(arr6,arr2)

print(id(arr6))
print(id(arr2))

arr6[0] = 23
print(arr6,arr2)


[67. 12.] [67. 12.]
1729295330800
1729541731600
[23. 12.] [67. 12.]


Converting 1D array into 2D array and vise-a-versa


In [ ]:

arr1 = array([
                [1,2,3],
                [4,5,6]               
            ])

print(arr1)
print(arr1.dtype) # shows the datatype of array
print(arr1.ndim)  # it provides dimensions
print(arr1.shape) # (rows,colums)
print(arr1.size)  # memory taken


In [ ]:
# 1. convert 2D array into 1D array.

arr2 = arr1.flatten()
print(arr2)


In [ ]:
# 2. convert 1D array into 2D.

arr3 = arr2.reshape(3,2) # specify (rows,columns)
print(arr3)


In [ ]:
# 3. convert 2D array into 3D. 

arr4 = array([
                [1,2,3,6,2,9],
                [4,5,6,7,5,3]               
            ])
arr5 = arr4.flatten() # first converted into 1D array
print(arr5)

print('----------------')
arr6 = arr5.reshape(2,2,3) # this creates a 3D array.this 3D array will have 2 2D arrays that will be printed.
print(arr6)
print('----------------')


Matrices


In [ ]:

arr1 = array([
                [1,2,3],
                [4,5,6]               
            ])
print(arr1)

print()
m1 = matrix(arr1)
print(m1) # the output looks similar.but with this we can perform more operations.

print()
m2 = matrix('1 2 3 ; 4 5 6 ; 7 8 9')
m3 = matrix('1 2 3 ; 4 5 6 ; 7 8 9')
print(m2)

print()
print(diagonal(m2)) # it gives the diagonal elements

print()
print(m2.max())

print()
m4 = m3 + m2
print(m4)

print()
print(m3*m2) # this is done automatically in python(following the rules of matrix multiplication)
# try doing it manually

In [ ]:
# Array Methods


# append()	Adds an element at the end of the list

# clear()	Removes all the elements from the list

# copy()	Returns a copy of the list

# count()	Returns the number of elements with the specified value

# extend()	Add the elements of a list (or any iterable), to the end of the current list

# index()	Returns the index of the first element with the specified value

# insert()	Adds an element at the specified position

# pop()	Removes the element at the specified position

# remove()	Removes the first item with the specified value

# reverse()	Reverses the order of the list

# sort()	Sorts the list
